import type { Metadata } from 'next'
import { IBM_Plex_Sans } from 'next/font/google'
import localFont from 'next/font/local'
import { Header } from '@/widgets/header/Header'
import { Footer } from '@/widgets/footer/Footer'
import './App.scss'

const IBM_FLEX_SANS = IBM_Plex_Sans({
  weight: ['300', '400', '500'],
  subsets: ['latin'],
})
export const my_font = localFont({
  src: './Whyte-Black.woff2',
  variable: '--font-whyte',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={my_font.variable}>
      <body className={IBM_FLEX_SANS.className}>
        <Header />
        <div className='header-height'></div>
        {children}
        <Footer />
      </body>
    </html>
  )
}
